### ISSUE TITLE
Rewrite the asset pipeline

### ISSUE THREAD

**Issue by little-bobby-tables** [fanuniverse/fanuniverse#1]
This issue may require several PRs to resolve it fully.

The main goal is replacing all **Gulp** scripts, which are practically unmaintainable due to a high amount of boilerplate code and manual dependency declarations, with **Webpack 2**.

Adjunct tasks:
- [ ] Replace UglifyJS with [Butternut](https://github.com/Rich-Harris/butternut).
- [ ] Test site usability in IE11 and Opera Mini, and if there are any serious issues, consider not supporting them.
- [x] Integrate production asset manifest into Phoenix views (currently, the application fetches `/app.css` and `/app.js` without revisions in all environments).

**Comment by liamwhite** [comment]
I'd just start with not supporting IE11 and Opera Mini, and then maybe decide to support them if it's not _that_ broken.

**Comment by little-bobby-tables** [comment]
There are just some polyfills (promises and fetch, namely) that could be dropped if those two browsers are out, same for autoprefixer.
